### ISSUE TITLE
xbash生成的二进制如何支持不同操作系统

### ISSUE THREAD

**Issue by godben** [chenzhch/xbash#2]
如上所述，如何静态编译同时支持例如CentOS7或CentOS8，当前在CentOS8编译的跑在CentOS7上会报错，/lib64/libc.so.6: version `GLIBC_2.25' not found (required by)

**Comment by chenzhch** [comment]
你试一下在CentOS7编译在CentOS8上跑，一般高版本会兼容低版本。这属于不同环境编译问题，我也不是很了解这方面内容。
